# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Separate_K_rpkm_new1 <- function(y, ROUNDS, Zcut, k, err = 1e-10) {
    .Call('_LTMGSCA_Separate_K_rpkm_new1', PACKAGE = 'LTMGSCA', y, ROUNDS, Zcut, k, err)
}

